### ISSUE TITLE
config.json required when trying to call via ruby api

### ISSUE THREAD

**Issue by joenguyen** [activenetwork-automation/vcoworkflows#25]
``` ruby
require 'vcoworkflows'

workflow = VcoWorkflows::Workflow.new('Set Private Key', 
                                      server: 'https://server:8281/', 
                                      verify_ssl: false, 
                                      username: 'jnguyen', 
                                      password: 'password')
```
returns
```
Users/jnguyen/.chefdk/gem/ruby/2.1.0/gems/vcoworkflows-0.2.1/lib/vcoworkflows/config.rb:66:in `read': No such file or directory @ rb_sysopen - /Users/jnguyen/.vcoworkflows/config.json (Errno::ENOENT)
	from /Users/jnguyen/.chefdk/gem/ruby/2.1.0/gems/vcoworkflows-0.2.1/lib/vcoworkflows/config.rb:66:in `load_config'
	from /Users/jnguyen/.chefdk/gem/ruby/2.1.0/gems/vcoworkflows-0.2.1/lib/vcoworkflows/config.rb:42:in `initialize'
	from /Users/jnguyen/.chefdk/gem/ruby/2.1.0/gems/vcoworkflows-0.2.1/lib/vcoworkflows/vcosession.rb:38:in `new'
	from /Users/jnguyen/.chefdk/gem/ruby/2.1.0/gems/vcoworkflows-0.2.1/lib/vcoworkflows/vcosession.rb:38:in `initialize'
	from /Users/jnguyen/.chefdk/gem/ruby/2.1.0/gems/vcoworkflows-0.2.1/lib/vcoworkflows/workflow.rb:119:in `new'
	from /Users/jnguyen/.chefdk/gem/ruby/2.1.0/gems/vcoworkflows-0.2.1/lib/vcoworkflows/workflow.rb:119:in `initialize'
	from ./test.rb:3:in `new'
	from ./test.rb:3:in `<main>'
```

**Comment by joenguyen** [comment]
sigh -- wrong parameter name.

server should be url
